os:
    - linux
    - osx
language: generic
sudo: required
dist: bionic
env:
    - SWIFT_VERSION=5.1.3
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
osx_image: xcode11.3
script:
    - swift build
