os:
    - linux
    - osx
language: generic
sudo: required
dist: bionic
env:
    - SWIFT_VERSION=5.8
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
osx_image: xcode14.3
script:
    - swift build
